Catelog of my things project
Hector096/catelog-of-my-things pull request #26
Opened 2022-01-14 11:40 UTC by Leandro-Barretoo

In this PR we created the following:

A console app that will help you to keep a record of different types of things you won: books, music albums, movies, and games. Everything will be based on the UML class diagram given. The data will be stored in JSON files and preparation of a database with tables structure analogical to your program's class structure.

2022-01-14 15:09 UTC, omar-labana requested changes
Hi team, 

Excellent work so far! 👌
You have implemented all the required features correctly. ✔️ 
All written tests and passing. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️

- [ ] [Project documentation - video presentation] is missing, please record it and attach it to the next review.
- [x] Kindly, update the README file with more information about your project. For example, how to run the project locally or virtually(repl.it) and what is the project about with some screenshots.
_Please, check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 15:09 UTC, omar-labana commented on src/modules/create_game.rb
> +module CreateGame
- [x] Creating a game crashes the program. I'd suggest using begin-rescue to catch these types of errors  
![image](https://user-images.githubusercontent.com/33767951/149531480-9d939b23-7876-4a03-bb7d-499cb05092de.png)

2022-01-14 15:09 UTC, omar-labana commented on src/book.rb
> +class Book < Item
- [ ] All public methods in all classes should have unit tests. please add tests for the rest of the classes.

2022-01-15 11:00 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi Team, 

Good job on implementing the suggested changes. Now the App is working fine and you have added more tests. Well Done.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 11:01 UTC, merged